spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to simple bank accounts related QA APIs"
  contactDetails:
    name: "Manoj QA"
    email: "madushankamanoj414_qa@gmail.com"
  onCallSupport: 0715147270